### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by T-byte-sketch** [Mave14/Rblxwild-Predictor#3]
May I ask why is the dll obfuscated oh and nice obfuscated bat code, why would you do that I tested this on an rdp and nothing happened lol just a complete fucking virus

**Comment by Mave14** [comment]
It's protected from leaks and detections. Please don't act like a smartass if you haven't educated yourself.

**Comment by T-byte-sketch** [comment]
I am far well more educated than you are, do not be dumb and act all innocent and close the issue because you don't want people to see your fake ass programs.
